// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2, arg3, arg4) {
  return window['go']['usecase']['TaskUseCase']['AddTask'](arg1, arg2, arg3, arg4);
}

export function DeleteTask(arg1) {
  return window['go']['usecase']['TaskUseCase']['DeleteTask'](arg1);
}

export function ListTasks(arg1, arg2, arg3) {
  return window['go']['usecase']['TaskUseCase']['ListTasks'](arg1, arg2, arg3);
}

export function ToggleDone(arg1) {
  return window['go']['usecase']['TaskUseCase']['ToggleDone'](arg1);
}
