// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function ListTasks(arg1:string,arg2:string,arg3:string):Promise<Array<dto.TaskDTO>>;

export function ToggleDone(arg1:string):Promise<void>;
