services:
  app:
    build: .
    environment:
      - CONN_STRING=postgres://postgres:1234@db:5433/tododb?sslmode=disable
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tododb
    ports:
      - "5433:5432"
